In [1]:
from pathlib import Path
import pandas as pd
import matplotlib.pyplot as plt
import vallenae as vae
from tqdm import tqdm
import numpy as np
import matplotlib.pyplot as plt
import pywt
import keras
from keras import layers

TRADB = Path(r"C:\all\vallen\plate-dataset\fiber-friction.tradb")
tradb=vae.io.TraDatabase(TRADB)
full_df = tradb.read()
df1=pd.DataFrame()
df1['data']=full_df['data']
df1['label']=0
df1

Tra: 100%|██████████| 7011/7011 [00:00<00:00, 34901.55it/s]


data  label
trai                                                           
3      [3.0445285e-06, 3.0445285e-06, -2.13117e-05, -...      0
4      [6.089057e-06, 0.0, 3.0445285e-06, 0.0, -9.133...      0
7      [3.0445285e-06, 6.089057e-06, 0.0, 0.0, -1.217...      0
8      [-3.0445285e-06, 6.089057e-06, 0.0, 3.0445285e...      0
11     [6.089057e-06, 2.13117e-05, 3.0445284e-05, 3.6...      0
...                                                  ...    ...
24118  [-3.0445285e-06, -9.133586e-06, -1.2178114e-05...      0
24119  [9.133586e-06, 6.089057e-06, 3.0445285e-06, -3...      0
24121  [-9.133586e-06, -9.133586e-06, -9.133586e-06, ...      0
24125  [0.0, 9.133586e-06, 9.133586e-06, 6.089057e-06...      0
24126  [-1.2178114e-05, -1.5222642e-05, -1.2178114e-0...      0

[7011 rows x 2 columns]

In [2]:
TRADB = Path(r"C:\all\vallen\plate-dataset\sand.tradb")
tradb=vae.io.TraDatabase(TRADB)
full_df = tradb.read()
df2=pd.DataFrame()
df2['data']=full_df['data']
df2['label']=1
df2

Tra: 100%|██████████| 6929/6929 [00:00<00:00, 19439.43it/s]


data  label
trai                                                           
5      [-3.0445285e-06, 0.0, -3.0445285e-06, -9.13358...      1
8      [-2.7400756e-05, -2.4356228e-05, -2.13117e-05,...      1
13     [1.2178114e-05, 1.2178114e-05, 1.2178114e-05, ...      1
16     [4.26234e-05, 3.3489814e-05, 3.0445284e-05, 2....      1
21     [-1.5222642e-05, -1.5222642e-05, 0.0, -3.04452...      1
...                                                  ...    ...
40384  [0.0, -3.0445285e-06, -3.0445285e-06, 3.044528...      1
40388  [0.0, 1.2178114e-05, 0.0, 3.0445285e-06, 3.044...      1
40399  [1.2178114e-05, 0.0, 3.0445285e-06, 3.0445285e...      1
40402  [1.5222642e-05, 9.133586e-06, 1.5222642e-05, 9...      1
40406  [-3.0445285e-06, -2.13117e-05, -3.0445285e-06,...      1

[6929 rows x 2 columns]

In [3]:
TRADB = Path(r"C:\all\vallen\plate-dataset\sand-friction.tradb")
tradb=vae.io.TraDatabase(TRADB)
full_df = tradb.read()
df3=pd.DataFrame()
df3['data']=full_df['data']
df3['label']=2
df3

Tra: 100%|██████████| 6988/6988 [00:00<00:00, 35452.00it/s]


data  label
trai                                                           
1      [9.133586e-06, 3.0445285e-06, 9.133586e-06, 1....      2
2      [0.0, 0.0, -1.5222642e-05, -1.2178114e-05, -3....      2
3      [6.089057e-06, 0.0, -9.133586e-06, -3.0445285e...      2
10     [-6.089057e-06, -1.5222642e-05, -9.133586e-06,...      2
11     [-3.0445285e-06, 0.0, 0.0, 6.089057e-06, 0.0, ...      2
...                                                  ...    ...
13578  [-3.0445285e-06, 3.0445285e-06, 6.089057e-06, ...      2
13581  [-3.0445285e-06, -3.0445285e-06, 3.0445285e-06...      2
13582  [-1.2178114e-05, -6.089057e-06, 3.0445285e-06,...      2
13583  [3.0445285e-06, -6.089057e-06, -6.089057e-06, ...      2
13584  [-3.0445285e-06, 6.089057e-06, 3.0445285e-06, ...      2

[6988 rows x 2 columns]

In [4]:
TRADB = Path(r"C:\all\vallen\plate-dataset\sherbet-powder.tradb")
tradb=vae.io.TraDatabase(TRADB)
full_df = tradb.read()
df4=pd.DataFrame()
df4['data']=full_df['data']
df4['label']=3
df4

Tra: 100%|██████████| 6929/6929 [00:00<00:00, 27378.40it/s]


data  label
trai                                                           
3      [-3.0445285e-06, -6.089057e-06, 0.0, -1.217811...      3
11     [6.089057e-06, 3.0445285e-06, 6.089057e-06, 9....      3
16     [6.089057e-06, 0.0, 6.089057e-06, 0.0, 6.08905...      3
18     [-1.5222642e-05, -2.13117e-05, -1.2178114e-05,...      3
23     [-9.133586e-06, -9.133586e-06, -1.2178114e-05,...      3
...                                                  ...    ...
31196  [-6.089057e-06, -3.0445285e-06, 0.0, -3.044528...      3
31197  [-3.0445285e-06, 0.0, 0.0, 3.0445285e-06, -3.0...      3
31198  [-6.089057e-06, -6.089057e-06, -1.2178114e-05,...      3
31204  [-3.0445285e-06, 6.089057e-06, 0.0, 6.089057e-...      3
31206  [3.0445285e-06, 3.0445285e-06, 6.089057e-06, 9...      3

[6929 rows x 2 columns]

In [5]:
result = pd.concat([df1, df2,df3,df4], ignore_index=True)
result

data  label
0      [3.0445285e-06, 3.0445285e-06, -2.13117e-05, -...      0
1      [6.089057e-06, 0.0, 3.0445285e-06, 0.0, -9.133...      0
2      [3.0445285e-06, 6.089057e-06, 0.0, 0.0, -1.217...      0
3      [-3.0445285e-06, 6.089057e-06, 0.0, 3.0445285e...      0
4      [6.089057e-06, 2.13117e-05, 3.0445284e-05, 3.6...      0
...                                                  ...    ...
27852  [-6.089057e-06, -3.0445285e-06, 0.0, -3.044528...      3
27853  [-3.0445285e-06, 0.0, 0.0, 3.0445285e-06, -3.0...      3
27854  [-6.089057e-06, -6.089057e-06, -1.2178114e-05,...      3
27855  [-3.0445285e-06, 6.089057e-06, 0.0, 6.089057e-...      3
27856  [3.0445285e-06, 3.0445285e-06, 6.089057e-06, 9...      3

[27857 rows x 2 columns]

In [6]:
a=result.drop(columns=['label'])
c=a["data"].tolist()
c

[array([ 3.0445285e-06,  3.0445285e-06, -2.1311700e-05, ...,
         5.1756986e-05,  4.8712456e-05,  4.8712456e-05], dtype=float32),
 array([ 6.0890570e-06,  0.0000000e+00,  3.0445285e-06, ...,
        -2.1311700e-05, -1.5222642e-05,  0.0000000e+00], dtype=float32),
 array([ 3.0445285e-06,  6.0890570e-06,  0.0000000e+00, ...,
        -2.7400756e-05, -1.2178114e-05, -1.2178114e-05], dtype=float32),
 array([-3.0445285e-06,  6.0890570e-06,  0.0000000e+00, ...,
         7.0024158e-05,  7.0024158e-05,  5.4801512e-05], dtype=float32),
 array([6.0890570e-06, 2.1311700e-05, 3.0445284e-05, ..., 3.0445285e-06,
        2.1311700e-05, 3.3489814e-05], dtype=float32),
 array([-6.0890570e-06, -3.0445285e-06,  0.0000000e+00, ...,
         2.4356228e-05,  1.8267172e-05,  2.4356228e-05], dtype=float32),
 array([6.0890570e-06, 0.0000000e+00, 3.0445285e-06, ..., 3.3489814e-05,
        4.2623400e-05, 5.1756986e-05], dtype=float32),
 array([ 3.0445284e-05,  3.0445284e-05,  1.8267172e-05, ...,
        -3.04

In [ ]:
k=[]
for i in range(len(c)) :

    l=c[i].tolist()
    k.append(l)
k

In [9]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
d= pad_sequences(k, padding='post',value=0,dtype='float32',maxlen=5000)
d


array([[ 3.04452851e-06,  3.04452851e-06, -2.13117000e-05, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 6.08905702e-06,  0.00000000e+00,  3.04452851e-06, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 1.43092839e-04,  1.24825674e-04,  1.09603025e-04, ...,
        -2.74007562e-05, -1.21781140e-05, -1.21781140e-05],
       ...,
       [-4.56679263e-05, -3.34898141e-05, -3.95788702e-05, ...,
        -4.26234001e-05, -3.95788702e-05, -3.65343440e-05],
       [-6.08905684e-05, -6.39350983e-05, -5.48015123e-05, ...,
         3.04452842e-05,  3.34898141e-05,  3.34898141e-05],
       [ 3.04452851e-06,  3.04452851e-06,  6.08905702e-06, ...,
         9.13358599e-06,  1.21781140e-05,  2.74007562e-05]], dtype=float32)

In [10]:
y=np.array(result['label'].values)
y

array([0, 0, 0, ..., 3, 3, 3], dtype=int64)

In [11]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(d, y, test_size=0.2, random_state=42)
x_train = np.expand_dims(x_train, axis=-1)
x_train.shape

(22285, 5000, 1)

In [12]:
x_test = np.expand_dims(x_test, axis=-1)
x_test.shape

(5572, 5000, 1)

In [13]:
n_classes = len(np.unique(y_train))
n_classes 

4

In [14]:
def transformer_encoder(inputs, head_size, num_heads, ff_dim, dropout=0):
    # Attention and Normalization
    x = layers.MultiHeadAttention(
        key_dim=head_size, num_heads=num_heads, dropout=dropout
    )(inputs, inputs)
    x = layers.Dropout(dropout)(x)
    x = layers.LayerNormalization(epsilon=1e-6)(x)
    res = x + inputs

    # Feed Forward Part
    x = layers.Conv1D(filters=ff_dim, kernel_size=1, activation="relu")(res)
    x = layers.Dropout(dropout)(x)
    x = layers.Conv1D(filters=inputs.shape[-1], kernel_size=1)(x)
    x = layers.LayerNormalization(epsilon=1e-6)(x)
    return x + res

In [15]:
def build_model(
    input_shape,
    head_size,
    num_heads,
    ff_dim,
    num_transformer_blocks,
    mlp_units,
    dropout=0,
    mlp_dropout=0,
):
    inputs = keras.Input(shape=input_shape)
    x = inputs
    for _ in range(num_transformer_blocks):
        x = transformer_encoder(x, head_size, num_heads, ff_dim, dropout)

    x = layers.GlobalAveragePooling1D(data_format="channels_last")(x)
    for dim in mlp_units:
        x = layers.Dense(dim, activation="relu")(x)
        x = layers.Dropout(mlp_dropout)(x)
    outputs = layers.Dense(n_classes, activation="softmax")(x)
    return keras.Model(inputs, outputs)

In [16]:
input_shape = x_train.shape[1:]

model = build_model(
    input_shape,
    head_size=256,
    num_heads=4,
    ff_dim=4,
    num_transformer_blocks=4,
    mlp_units=[128],
    mlp_dropout=0.4,
    dropout=0.25,
)

model.compile(
    loss="sparse_categorical_crossentropy",
    optimizer=keras.optimizers.Adam(learning_rate=1e-4),
    metrics=["sparse_categorical_accuracy"],
)
model.summary()

callbacks = [    keras.callbacks.ModelCheckpoint(
        filepath="transformer_model.keras",
        save_best_only=True,
        monitor="val_loss")]

history = model.fit(
    x_train,
    y_train,
    validation_split=0.2,
    epochs=50,
    batch_size=16,
    callbacks=callbacks,
)

model.evaluate(x_test, y_test, verbose=1)

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_1 (InputLayer)           [(None, 5000, 1)]    0           []                               
                                                                                                  
 multi_head_attention (MultiHea  (None, 5000, 1)     7169        ['input_1[0][0]',                
 dAttention)                                                      'input_1[0][0]']                
                                                                                                  
 dropout (Dropout)              (None, 5000, 1)      0           ['multi_head_attention[0][0]']   
                                                                                                  
 layer_normalization (LayerNorm  (None, 5000, 1)     2           ['dropout[0][0]']            

: 